# Generated by Django 3.1.5 on 2021-08-04 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_cargo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='send_cargo',
            old_name='rider_send',
            new_name='rider',
        ),
        migrations.RenameField(
            model_name='send_cargo',
            old_name='status_cargo',
            new_name='status',
        ),
    ]
