# Generated by Django 3.1.5 on 2021-08-17 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_cargo', '0002_auto_20210805_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='send_cargo',
            name='cargo_note',
            field=models.CharField(default=None, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='send_cargo',
            name='cargo_weight',
            field=models.FloatField(default=10, validators=[django.core.validators.MinValueValidator(0.001), django.core.validators.MaxValueValidator(1000)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='send_cargo',
            name='get_cargo_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='send_cargo',
            name='phone_number_get_cargo',
            field=models.CharField(default=1111, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{8,15}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_inf',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
