# Generated by Django 3.1.5 on 2021-08-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_cargo', '0003_auto_20210817_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send_cargo',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('STARTED', 'STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('CANCELD', 'CANCELD')], default='REQUESTED', max_length=20),
        ),
    ]
