# Generated by Django 3.1.5 on 2021-09-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_cargo', '0005_auto_20210916_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='send_cargo',
            name='cargo_distance',
            field=models.CharField(default=10, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='send_cargo',
            name='cargo_price',
            field=models.CharField(default=10, max_length=10),
            preserve_default=False,
        ),
    ]
