# Generated by Django 3.1.5 on 2021-09-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_cargo', '0006_auto_20210916_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send_cargo',
            name='cargo_distance',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='send_cargo',
            name='cargo_price',
            field=models.CharField(max_length=100),
        ),
    ]
