# Generated by Django 3.1.5 on 2021-10-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_cargo', '0008_auto_20210917_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='send_cargo',
            options={'verbose_name': 'Manage Trip of cargo', 'verbose_name_plural': 'Manage Trip of cargo'},
        ),
        migrations.AlterModelOptions(
            name='user_inf',
            options={'verbose_name': 'Manage User account', 'verbose_name_plural': 'Manage User account'},
        ),
    ]
