# Generated by Django 3.1.5 on 2021-10-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_cargo', '0009_auto_20211002_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_inf',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user_inf',
            name='username',
            field=models.CharField(default='root', max_length=225),
        ),
    ]
