# Generated by Django 3.1.5 on 2021-10-29 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_cargo', '0010_auto_20211002_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='send_cargo',
            name='cargo_distance',
        ),
        migrations.RemoveField(
            model_name='send_cargo',
            name='cargo_price',
        ),
    ]
