# Generated by Django 3.1.5 on 2021-11-02 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_cargo', '0011_auto_20211030_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='send_cargo',
            name='cargo_distance',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1e-06), django.core.validators.MaxValueValidator(1000)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='send_cargo',
            name='cargo_price',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
